application: cert-apps
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: 7d

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /profile/.*
  script: handlers.profile.app
- url: /.*
  script: handlers.landing.app
